name: clap-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - alembic=1.14.0
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - attrs=24.3.0
  - audioread=3.0.1
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.8
  - aws-sdk-cpp=1.11.458
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - contourpy=1.3.0
  - cpython=3.9.21
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-opencl-dev=12.6.77
  - cuda-profiler-api=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - cycler=0.12.1
  - datasets=3.2.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - double-conversion=3.3.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.9.0
  - graphite2=1.3.13
  - greenlet=3.1.1
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=10.2.0
  - hdf5=1.14.4
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.27.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2025.0.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.23
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libglib=2.82.2
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvfatbin-dev=12.6.77
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libogg=1.3.5
  - libopus=1.3.1
  - libparquet=18.1.0
  - libpng=1.6.45
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librosa=0.10.2.post1
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libuv=1.49.2
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.16
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightning-utilities=0.11.9
  - lz4-c=1.10.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mako=1.3.8
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mistune=3.1.0
  - mkl=2023.1.0
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.5.1
  - nbclassic=1.2.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.5
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - openjpeg=2.5.3
  - openssl=3.4.0
  - optuna=4.1.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - propcache=0.2.1
  - psutil=6.1.1
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pydub=0.25.1
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyparsing=3.2.1
  - pyside6=6.8.1
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch-cuda=12.4
  - pytorch-metric-learning=2.8.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.6.0
  - pywin32=307
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.8.1
  - re2=2024.07.02
  - referencing=0.35.1
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - safetensors=0.5.2
  - scikit-fuzzy=0.5.0
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - sqlalchemy=2.0.37
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tbb=2021.13.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tomli=2.2.1
  - torchmetrics=1.6.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.48.0
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - fast-bss-eval==0.1.4
      - llvmlite==0.41.1
      - msclap==1.3.3
      - numba==0.58.1
      - numpy==1.26.4
      - ssspy==0.1.7
      - sympy==1.13.1
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchlibrosa==0.1.0
      - torchvision==0.16.2
